#!/bin/sh
open /Library/Input\ Methods/VarnamIME.app
sleep 1
until ./installer --register
do
  sleep 1
done
until ./installer --enable
do
  sleep 1
done
/Library/Input\ Methods/VarnamIME.app/Contents/MacOS/VarnamIME -import
exit 0
